-- 商品マスタ。
-- 商品の注文可否、価格、在庫を管理する。
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price NUMERIC(12, 0) NOT NULL CHECK (price > 0),
    stock_quantity INTEGER NOT NULL CHECK (stock_quantity >= 0),
    active BOOLEAN NOT NULL
);

-- 注文ヘッダ。
-- 注文状態、配送先、金額、作成・キャンセル日時を保持する。
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL CHECK (
        status IN ('CREATED', 'CONFIRMED', 'SHIPPED', 'CANCELLED')
    ),
    shipping_postal_code VARCHAR(7) NOT NULL CHECK (shipping_postal_code ~ '^[0-9]{7}$'),
    subtotal NUMERIC(12, 0) NOT NULL CHECK (subtotal >= 0),
    discount_amount NUMERIC(12, 0) NOT NULL CHECK (discount_amount >= 0),
    shipping_fee NUMERIC(12, 0) NOT NULL CHECK (shipping_fee >= 0),
    total_amount NUMERIC(12, 0) NOT NULL CHECK (total_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    cancelled_at TIMESTAMPTZ
);

-- 注文明細。
-- Product の現在値ではなく、注文時点の商品名・単価を Snapshot として保持する。
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    unit_price NUMERIC(12, 0) NOT NULL CHECK (unit_price > 0),
    quantity INTEGER NOT NULL CHECK (
        quantity BETWEEN 1
        AND 99
    ),
    line_amount NUMERIC(12, 0) NOT NULL CHECK (line_amount >= 0),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id)
);

-- 注文状態と作成日時による一覧検索・並び替えを補助する Index。
CREATE INDEX IF NOT EXISTS idx_orders_status_created_at ON orders (status, created_at DESC);

-- Order ID を利用した注文明細取得を補助する Index。
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
